/// Flutter icons Pihole
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com, Pi-hole
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Pihole
///      fonts:
///       - asset: fonts/Pihole.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Pihole {
  Pihole._();

  static const _kFontFam = 'Pihole';
  // static const String? _kFontPkg = null;

  static const IconData pi_hole = IconData(0xe800, fontFamily: _kFontFam, fontPackage: null);
}
